### ISSUE TITLE
Service configuration data not being put in services.conf file

### ISSUE THREAD

**Issue by sidneydrill** [eapowertools/iPortal#32]
iPortal wizard doesn't automatically do the following (step 5 of the manual process), which prevents the user from connecting with port 3090 after going through the wizard. After manually do this step (and refreshing), it worked perfectly.

"Add the service configuration data to the [QLIK_INSTALL]\ServiceDispatcher\services.conf file. The last line of the configuration data must point to the server.js file located in the root directory of your cloned iPortal project."

**Comment by goldbergjeffrey** [comment]
So a couple of things here.  

A: we should deprecate the manual install of iPortal.  It's much easier to use the install and the items you would want to change post installation are things like udc content and such which aren't part of the manual install anyway.

B: Because the manual config is old, it doesn't reflect the fact that iPortal does not use the Qlik Sense service dispatcher.  We now package our own service dispatcher along with all the powertools installs.  This is in response to the eventual (I have no idea when, why, how) deprecation of the shipped service dispatcher and corresponding service.

**Comment by sidneydrill** [comment]
Ok - so what needs to be fixed to have port 3090 open automatically? I went through the auto-install, and then ran into the connection error. Another user had posted on community that they copied the data in services.conf (re the manual steps), so I tried that and it worked. Is there something missing from the wizard that would lead to this error?

**Comment by goldbergjeffrey** [comment]
Resolved.  The installer was not pointing to the correct services.conf file.
