### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by arulsettu** [eapowertools/iPortal#34]
it throws runtime error(at 25:202)

**Comment by goldbergjeffrey** [comment]
@arulsettu please upload some screenshots and information about the environment you are installing on plus operating system and Qlik Sense Enterprise server version.

thanks!

**Comment by arulsettu** [comment]
@goldbergjeffrey  Thanks for the reply

server details are 

windows server 2012 R2
qlik sense june 2017 patch 2
qlik sense server 11.11.3

error message:
![capture](https://user-images.githubusercontent.com/5644016/30579578-ecc5c750-9d36-11e7-8a24-c1ebe400d371.JPG)


Authentication module redirect URI is like :
 
https://servername.com:3090/
 
when i try it says url not found.

**Comment by goldbergjeffrey** [comment]
Hi, see you closed the issue, but for others I want to clarify why this is happening.  Unfortunately, the code needs to be installed in the eapowertools folder (the default location for all eapowertools) because we built our own service dispatcher to decouple from the Qlik Sense provided service dispatcher.  What this means is that when you attempt to install in a different location than eapowertools the installer can't find the service dispatcher located in the eapowertools folder and consequently the installer gacks.  We are working on changing the way we install software across all of our solutions.

**Comment by arulsettu** [comment]
sorry by mistake i closed. actually looking for solution. so if i install in the default location it will work ?

**Comment by arulsettu** [comment]
HI Jeff,
              Thanks for the solution. it worked as per your suggestion
